/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface SouthAfricaVotingInterface extends Interface {
    getFunction(nameOrSignature: "addCandidate" | "admin" | "candidates" | "candidatesCount" | "changePhase" | "getCandidate" | "hasVotedAlready" | "isRegistered" | "phase" | "registerVoter" | "vote"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CandidateAdded" | "PhaseChanged" | "Voted" | "VoterRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'addCandidate', values: [string]): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'candidates', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'candidatesCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'changePhase', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCandidate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasVotedAlready', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isRegistered', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'phase', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerVoter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'candidates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'candidatesCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'changePhase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVotedAlready', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'phase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerVoter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  
    export namespace CandidateAddedEvent {
      export type InputTuple = [candidateId: BigNumberish, name: string];
      export type OutputTuple = [candidateId: bigint, name: string];
      export interface OutputObject {candidateId: bigint, name: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PhaseChangedEvent {
      export type InputTuple = [newPhase: BigNumberish];
      export type OutputTuple = [newPhase: bigint];
      export interface OutputObject {newPhase: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotedEvent {
      export type InputTuple = [voter: AddressLike, candidateId: BigNumberish];
      export type OutputTuple = [voter: string, candidateId: bigint];
      export interface OutputObject {voter: string, candidateId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoterRegisteredEvent {
      export type InputTuple = [voter: AddressLike];
      export type OutputTuple = [voter: string];
      export interface OutputObject {voter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SouthAfricaVoting extends BaseContract {
    
    connect(runner?: ContractRunner | null): SouthAfricaVoting;
    waitForDeployment(): Promise<this>;

    interface: SouthAfricaVotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addCandidate: TypedContractMethod<
      [_name: string, ],
      [void],
      'nonpayable'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    candidates: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint] & {id: bigint, name: string, voteCount: bigint }],
      'view'
    >
    

    
    candidatesCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    changePhase: TypedContractMethod<
      [_phase: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getCandidate: TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [[string, bigint] & {name: string, voteCount: bigint }],
      'view'
    >
    

    
    hasVotedAlready: TypedContractMethod<
      [_voter: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isRegistered: TypedContractMethod<
      [_voter: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    phase: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    registerVoter: TypedContractMethod<
      [_voter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    vote: TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addCandidate'): TypedContractMethod<
      [_name: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'candidates'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint] & {id: bigint, name: string, voteCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'candidatesCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'changePhase'): TypedContractMethod<
      [_phase: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCandidate'): TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [[string, bigint] & {name: string, voteCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'hasVotedAlready'): TypedContractMethod<
      [_voter: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRegistered'): TypedContractMethod<
      [_voter: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'phase'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registerVoter'): TypedContractMethod<
      [_voter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CandidateAdded'): TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
getEvent(key: 'PhaseChanged'): TypedContractEvent<PhaseChangedEvent.InputTuple, PhaseChangedEvent.OutputTuple, PhaseChangedEvent.OutputObject>;
getEvent(key: 'Voted'): TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
getEvent(key: 'VoterRegistered'): TypedContractEvent<VoterRegisteredEvent.InputTuple, VoterRegisteredEvent.OutputTuple, VoterRegisteredEvent.OutputObject>;

    filters: {
      
      'CandidateAdded(uint256,string)': TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
      CandidateAdded: TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
    

      'PhaseChanged(uint8)': TypedContractEvent<PhaseChangedEvent.InputTuple, PhaseChangedEvent.OutputTuple, PhaseChangedEvent.OutputObject>;
      PhaseChanged: TypedContractEvent<PhaseChangedEvent.InputTuple, PhaseChangedEvent.OutputTuple, PhaseChangedEvent.OutputObject>;
    

      'Voted(address,uint256)': TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
      Voted: TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
    

      'VoterRegistered(address)': TypedContractEvent<VoterRegisteredEvent.InputTuple, VoterRegisteredEvent.OutputTuple, VoterRegisteredEvent.OutputObject>;
      VoterRegistered: TypedContractEvent<VoterRegisteredEvent.InputTuple, VoterRegisteredEvent.OutputTuple, VoterRegisteredEvent.OutputObject>;
    
    };
  }